server:
    address: 0.0.0.0
    port: 8686
spring:
    cache:
        type: redis
    redis:
        database: 0         # Redis数据库索引（默认为0）
        host: 127.0.0.1     # Redis服务器地址
        pool:
            max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
            max-idle: 8     # 连接池中的最大空闲连接
            max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
            min-idle: 0     # 连接池中的最小空闲连接
        port: 6379          # Redis服务器连接端口
        timeout: 2000       # 连接超时时间（毫秒）
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/test
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/taro?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-not-delete-value: 1
            logic-delete-value: 0

